on:
  workflow_dispatch:

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Azure VM and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/sbsnext/sbsnext-site:latest
            docker-compose down
            docker-compose up -d