on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Azure VM and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            echo "🔄 Pulling latest changes from GitHub..."
            cd ~/sbsnext || git clone https://github.com/acostmig/sbsnext.git ~/sbsnext
            cd ~/sbsnext
            git fetch origin
            git checkout $COMMIT_HASH || git checkout main  # ✅ Checkout the exact commit or fallback to main
            git reset --hard
            git pull origin $COMMIT_HASH || git pull origin main  # Ensure latest changes

            sudo chmod 666 /var/run/docker.sock  # ✅ Fix permission issue

            echo "Logging into GitHub Container Registry (GHCR)..."
            echo "${{ secrets.GHCR_PAT }}" | sudo -S docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "Stopping old containers..."
            docker-compose down

            echo " Pulling latest images..."
            docker-compose pull

            echo "Starting services..."
            docker-compose up -d --remove-orphans
